version: '3.0'

networks: 
    production-network:                                         # Define o nome do network
        driver: bridge

services:
  noticias_web:
    container_name: container-kube-noticias
    image: jnlucas/image-phpmysql:latest
    volumes:
      - ./noticias:/var/www/html

    working_dir: /var/www/html/
    ports:
      - "8588:80"
    networks: 
      - production-network  

  sistema_web:
    container_name: container-kube
    image: jnlucas/image-phpmysql:latest
    volumes:
      - ./sistema:/var/www/html

    working_dir: /var/www/html/
    ports:
      - "8587:80"
    networks: 
      - production-network 

  db:
    image: mysql:5.7
    container_name: container_mysql
    volumes:
      - ./mysql:/home

    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'empresa'
      #MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'q1w2e3r4'
      MYSQL_ROOT_PASSWORD: 'q1w2e3r4'
    networks: 
      - production-network 

