apiVersion: v1
kind: Service
metadata:
  name: db                                            # nome de servico usado na Connection String
spec:
  type: ClusterIP                                     # Acessado somente pelos pods do clustes
  ports:
    - name: http
      port: 3306
  selector:
    name: mysql                                       # mesmo nome dado template/../name do statefulset-mysql.yaml
