apiVersion: v1                                      #versao do Kubernetes
kind: Pod                                           #tipo de objeto
metadata:
  name: aplicaco-noticia                            #nome 
spec:
  containers:                                       #containers
    - name: container-aplicacao
      image: jnlucas/image-phpmysql:latest
      ports:
        - containerPort: 80
